SELECT
    P.NO_SERIE,F.NO_SERIE
FROM
    OBJET F
    INNER JOIN
    (OBJET P INNER JOIN OBJPEREFILS O ON P.C_OBJET=O.C_OBJET_PERE)ON F.C_OBJET=O.C_OBJET
WHERE P.C_NATURE='INF' AND P.D_ARCHIVE IS NULL AND F.D_ARCHIVE IS NULL  AND D_HISTLIAISON is null 



SELECT * from UTILAFFECTHAB 
WHERE I_HAB_RH <> 1 

SELECT T.L_TYPEHAB,T.L_COMMENT FROM TYPEHAB T WHERE T.L_TYPEHAB LIKE '%GTL%' OR T.L_TYPEHAB LIKE '%ARI%' OR T.L_TYPEHAB LIKE '%MTI%' OR T.L_TYPEHAB LIKE '%HAB%' OR T.L_TYPEHAB LIKE '%TRS%' order by T.L_TYPEHAB


SELECT U.N_UTIL,U.PRE_UTIL,U.I_UTI_MATRICULERH,H.T_UTILAFFECT,H.C_PROFIL,T.L_TYPEHAB,H.I_HAB_RH,H.I_HAB_DDEB,H.I_HAB_DFIN,H.ST_UTILAFFECT,T.* FROM UTILAFFECTHAB H INNER JOIN UTILISATEUR U ON U.C_UTIL=H.C_UTIL INNER JOIN TYPEHAB T ON T.C_TYPEHAB=H.C_TYPEHAB
WHERE H.I_HAB_RH <> 1 and  H.C_PROFIL IN ('GEST','SINISTRE','INTERVENAN','ACHATSTOCK') /*and U.C_SERVICE  like '03030101%'*/ AND H.ST_UTILAFFECT='A'  order by U.N_UTIL

SELECT
    U.N_UTIL,
    U.PRE_UTIL,
    U.I_UTI_MATRICULERH,
    H.T_UTILAFFECT,
    H.C_PROFIL,
    T.L_TYPEHAB,
    H.C_SITE,
    H.C_FONCTION,
    H.I_HAB_RH,
    H.I_HAB_DDEB,
    H.I_HAB_DFIN,
    H.ST_UTILAFFECT
FROM
    UTILAFFECTHAB H INNER JOIN UTILISATEUR U ON U.C_UTIL=H.C_UTIL INNER JOIN TYPEHAB T ON T.C_TYPEHAB=H.C_TYPEHAB
WHERE H.T_UTILAFFECT='D' AND H.I_HAB_RH <> 1 and  H.C_PROFIL IN ('GEST','SINISTRE','INTERVENAN','ACHATSTOCK') /*and U.C_SERVICE  like '03030101%'*/ AND H.ST_UTILAFFECT='A' /*AND (T.L_TYPEHAB LIKE '%GTL%' OR T.L_TYPEHAB LIKE '%ARI%' OR T.L_TYPEHAB LIKE '%MTI%' OR T.L_TYPEHAB LIKE '%HAB%' OR T.L_TYPEHAB LIKE '%TRS%' OR T.L_TYPEHAB LIKE '%ATL%')*/ AND H.D_ARCHIVE IS NULL

ORDER BY U.N_UTIL

SELECT T.L_TYPEHAB,S.C_SITEBARRE,HC.C_FONCTION FROM UTILAFFECTHAB HC LEFT JOIN TYPEHAB T ON HC.C_TYPEHAB=T.C_TYPEHAB LEFT JOIN SITE S ON S.C_SITE=HC.C_SITE  WHERE HC.C_PROFIL IN ('GEST','SINISTRE','INTERVENAN','ACHATSTOCK') AND T.L_TYPEHAB LIKE 'GTL%' AND C_SITEBARRE <> 'S047'  /*group by T.L_TYPEHAB,S.C_SITEBARRE,HC.C_FONCTION */order by T.L_TYPEHAB

select * from TYPEHABEQUIPE

select * from TYPEHABNATURE

SELECT * FROM TYPEHAB

SELECT * FROM UTILAFFECTHAB

select H.L_TYPEHAB,E.C_EQUIPE from TYPEHAB H LEFT JOIN  TYPEHABEQUIPE E ON E.C_TYPEHAB=H.C_TYPEHAB WHERE H.L_TYPEHAB LIKE 'GTL%'

select H.L_TYPEHAB,N.C_NATURE,N.F_LECTURESEULE from TYPEHAB H LEFT JOIN  TYPEHABNATURE N ON N.C_TYPEHAB=H.C_TYPEHAB WHERE H.L_TYPEHAB LIKE 'GTL%'


DELETE H FROM UTILAFFECTHAB H INNER JOIN UTILISATEUR
U ON U.C_UTIL=H.C_UTIL INNER JOIN TYPEHAB T ON T.C_TYPEHAB=H.C_TYPEHAB
/*WHERE H.I_HAB_RH <> 1 and  H.C_PROFIL IN ('GEST','SINISTRE','INTERVENAN','ACHATSTOCK') AND U.C_SERVICE  LIKE '03030101%' AND H.ST_UTILAFFECT='A'  */
WHERE H.I_HAB_RH <> 1 and  H.C_PROFIL IN ('GEST','SINISTRE','INTERVENAN','ACHATSTOCK')  /*AND H.ST_UTILAFFECT='A'*/ AND (T.L_TYPEHAB LIKE '%GTL%' OR T.L_TYPEHAB LIKE '%ARI%' OR T.L_TYPEHAB LIKE '%MTI%' OR T.L_TYPEHAB LIKE '%HAB%' OR T.L_TYPEHAB LIKE '%TRS%' OR T.L_TYPEHAB LIKE '%ATL%') AND H.D_ARCHIVE IS NULL

SELECT * FROM TYPEHAB T WHERE (T.L_TYPEHAB LIKE '%GTL%' OR T.L_TYPEHAB LIKE '%ARI%' OR T.L_TYPEHAB LIKE '%MTI%' OR T.L_TYPEHAB LIKE '%HAB%' OR T.L_TYPEHAB LIKE '%TRS%' OR T.L_TYPEHAB LIKE '%ATL%') Order BY T.L_TYPEHAB

SELECT * FROM UTILEQUIP WHERE C_PROFIL='CLIENT' AND C_EQUIPE <> 'CLIENT' AND C_EQUIPE LIkE 'I%' order by C_EQUIPE
select N_UTIL FROM UTILISATEUR WHERE C_UTIL='83334'

UPDATE UTILAFFECTHAB SET /*ST_UTILAFFECT='D',*/ I_HAB_DFIN='07/12/2100' 
SELECT U.N_UTIL,H.* FROM UTILAFFECTHAB H INNER JOIN UTILISATEUR U ON H.C_UTIL=U.C_UTIL WHERE H.I_HAB_RH <> 1 AND H.C_PROFIL NOT LIKE 'RESP%' /*AND ST_UTILAFFECT='A'*/ AND H.D_ARCHIVE IS NULL /*AND T_UTILAFFECT='D'*/
