SELECT
    U.N_UTIL AS NOM,
    U.PRE_UTIL AS PRENOM,
    F.L_FONCTION AS FONCTION,
    S2.N_SERVICE AS GROUPEMENT,
    S3.N_SERVICE AS SERVICE

FROM
    UTILISATEUR U INNER JOIN SERVICE S ON U.C_SERVICE=S.C_SERVICE,
    SERVICE S2,
    SERVICE S3,
    FONCTION F
WHERE  U.C_FONCTION LIKE 'CDST' AND S.L_FULLNAMESERVICE LIKE '%SOUT. TECH.%' AND S2.C_SERVICE=LEFT(S.C_SERVICE,8) AND S3.C_SERVICE=LEFT(S.C_SERVICE,10) AND F.C_FONCTION=U.C_FONCTION
ORDER BY S2.N_SERVICE,S3.N_SERVICE

/*
SELECT
    count(*) AS NB,
    U.C_FONCTION AS FONCTION
FROM
    UTILISATEUR U
GROUP BY U.C_FONCTION
ORDER BY NB


SELECT * from FONCTION*/
SELECT C_UTIL_DEM FROM suiteisilog.APPEL

SELECT N_UTIL,I_UTI_MATRICULERH,* FROM suiteisilog.UTILISATEUR WHERE I_UTI_MATRICULERH='21803'
