SELECT
    U.N_UTIL AS NOM,
    U.PRE_UTIL AS PRENOM,
    U.C_FONCTION AS FONCTION,
    S2.N_SERVICE AS GROUPEMENT,
    S3.N_SERVICE AS SERVICE

FROM
    UTILISATEUR U INNER JOIN SERVICE S ON U.C_SERVICE=S.C_SERVICE, SERVICE S2, SERVICE S3
WHERE  U.C_FONCTION LIKE 'CDCADJ%' AND/* S.L_FULLNAMESERVICE LIKE '%SOUT. TECH.%' AND */S2.C_SERVICE=LEFT(S.C_SERVICE,8) AND S3.C_SERVICE=LEFT(S.C_SERVICE,10)
ORDER BY S2.N_SERVICE,S3.N_SERVICE

/*
SELECT
    count(*) AS NB,
    U.C_FONCTION AS FONCTION
FROM
    UTILISATEUR U
GROUP BY U.C_FONCTION
ORDER BY NB
*/