SELECT
    S.I_UO_LIBLONG,
    U.N_UTIL,
    U.PRE_UTIL,
    U.I_UTI_MATRICULERH,
    F.L_FONCTION
FROM
    UTILAFFECT H,
    FONCTION F,
    UTILISATEUR U,
    SERVICE S
WHERE  H.C_PROFIL='CLIENT' AND H.I_HAB_SITUATION IS NULL AND H.C_FONCTION=F.C_FONCTION AND U.C_UTIL=H.C_UTIL AND S.C_SERVICE=LEFT(U.C_SERVICE,10) AND U.D_ARCHIVE IS NULL AND T_UTILAFFECT='C' 



