SELECT
  IIF (U.N_UTIL IS NULL, K.VA_CARACOBJ + ' ' + S.C_SERVICEBARRE,U.N_UTIL + ' ' + U.PRE_UTIL) AS 'NOM COMPLET',
  U.I_UTI_MATRICULERH ,
  IIF (U.N_UTIL IS NULL, K.VA_CARACOBJ,U.N_UTIL) AS NOM,
  IIF (U.N_UTIL IS NULL, S.C_SERVICEBARRE,U.PRE_UTIL) AS PRENOM,
  U.D_NAISSANCE,
  G.L_LOV_VALUE,
  U.AD_UTILEMAIL,
  S.C_SERVICEBARRE,
  S.L_FULLNAMESERVICE,
  K.VA_CARACOBJ,
  'LGME' AS CATEGORIE,
  'SDIS13' AS SOCIETE,
  FO.L_FONCTION,
  FORMAT(cast(O.NO_SERIE as int), '+33 # ## ## ## ##') AS TEL
FROM
  OBJET O LEFT JOIN (FONCTION FO RIGHT JOIN (Z_LOV_VALUE G RIGHT JOIN UTILISATEUR U ON U.C_LOV_GRADE=G.C_LOV_VALUE)ON FO.C_FONCTION=U.C_FONCTION)ON O.C_UTIL=U.C_UTIL,
  FAMOBJ F,
  TYPOBJ T,
  CATALOGUE C,
  CARACOBJ K,
  SERVICE S
WHERE /*O.C_NATURE='INF' AND O.C_BARRE LIKE 'SIM%' AND */O.C_REF=C.C_REF AND C.C_TYPOBJ=T.C_TYPOBJ AND T.C_FAMOBJ=F.C_FAMOBJ AND O.C_OBJET=K.C_OBJET
 AND F.L_FAMOBJ ='ABONNEMENT MOBILE'  AND T.L_TYPOBJ LIKE '%VOIX%' AND O.C_SITE<>'51783' AND K.C_CARAC='IUTILGEN' AND O.C_SERVICE=S.C_SERVICE AND K.D_HISTCARACOBJ is NULL AND O.D_ARCHIVE is NULL 
 ORDER BY U.N_UTIL