
/*
SELECT DISTINCT L.NAME, L.VERSION, CHARINDEX(CHAR(160),L.NAME)
FROM   Openquery (OCS, 'SELECT S.NAME, S.VERSION FROM softwares S WHERE  S.NAME LIKE "%Microsoft Office Standard%2013" AND locate(CHAR(160),S.NAME)=0') L


SELECT
    L.NAME,
    L.VERSION,
    CHARINDEX(CHAR(160),L.NAME) *,CHARINDEX(CHAR(160),L.NOM),CHARINDEX(CHAR(160),L.TOTO)
FROM
    OPENQUERY (OCS, 'SELECT DISTINCT REPLACE(S.NAME, CHAR(160) , CHAR(32))AS TOTO ,S.VERSION,S.ID, H.NAME, S.NAME AS NOM from softwares S inner join  (SELECT MAX(ID) AS ID ,NAME, LASTDATE FROM hardware  WHERE LASTDATE > DATE_ADD( CURDATE() ,INTERVAL -2 YEAR) GROUP BY NAME) H ON S.HARDWARE_ID=H.ID') L
--WHERE L.NAME LIKE '%Microsoft Office Standard%2013'
WHERE L.NAME='B18U096' AND L.NOM LIKE '%Microsoft Office Standard%2013'
*/

SELECT DISTINCT L.NAME, L.VERSION, CHARINDEX(CHAR(160),L.NAME)
FROM   Openquery (OCS, 'SELECT S.NAME, S.VERSION FROM softwares S WHERE  S.NAME LIKE "ADOBE%"') L
WHERE L.NAME LIKE 'ADOBE [RA][EC][AR]%'

