

select * from CARACOBJ C /*where C.VA_CARACOBJ='ORANGE'*/

select U.N_UTIL,U.I_UTI_MATRICULERH from UTILISATEUR U where U.I_UTI_MATRICULERH is  NULL

select O.N_OBJET, O.I_OBJ_OCS_RESEAU_SDIS, O.I_OBJ_OCS_SITE_RESEAU,U.I_UTI_MATRICULERH,U.N_UTIL,PRE_UTIL
from (suiteisilog.OBJET O left join [suiteisilog].[CATALOGUE]  C on C.C_REF=O.C_REF) INNER JOIN UTILISATEUR U on U.C_UTIL=O.C_UTIL
Where O.C_NATURE='INF' and C.C_FAMOBJ='IUNITE' and O.C_STOBJ='EE'

select C_SITE,C_SITE_PERE,C_SITEBARRE,N_SITE,T_LOVSITE from SITE WHERE C_ROLESITE='P'and T_LOVSITE is not NULL

select C_SERVICE,C_SERVICE_PERE,N_SERVICE,C_SERVICEBARRE,* from SERVICE where  (C_SERVICE_PERE <> 'ASTRE' or C_SERVICE_PERE is null) AND C_SERVICE <> 'ASTRE' 


select * FROM SPECIF_V_OCS_POSTES

select * f