

SELECT
    *
FROM
    CARACOBJ C
/*where C.VA_CARACOBJ='ORANGE'*/

SELECT
    U.N_UTIL,
    U.I_UTI_MATRICULERH
FROM
    UTILISATEUR U
WHERE U.I_UTI_MATRICULERH IS  NULL

SELECT
    O.N_OBJET,
    O.I_OBJ_OCS_RESEAU_SDIS,
    O.I_OBJ_OCS_SITE_RESEAU,
    U.I_UTI_MATRICULERH,
    U.N_UTIL,
    PRE_UTIL
FROM
    (suiteisilog.OBJET O LEFT JOIN [suiteisilog].[CATALOGUE]  C ON C.C_REF=O.C_REF) INNER JOIN UTILISATEUR U ON U.C_UTIL=O.C_UTIL
WHERE O.C_NATURE='INF' AND C.C_FAMOBJ='IUNITE' AND O.C_STOBJ='EE'

SELECT
    C_SITE,
    C_SITE_PERE,
    C_SITEBARRE,
    N_SITE,
    T_LOVSITE
FROM
    SITE
WHERE C_ROLESITE='P'AND T_LOVSITE IS NOT NULL

SELECT
    C_SERVICE,
    C_SERVICE_PERE,
    N_SERVICE,
    C_SERVICEBARRE,
    *
FROM
    SERVICE
WHERE  (C_SERVICE_PERE <> 'ASTRE' OR C_SERVICE_PERE IS NULL) AND C_SERVICE <> 'ASTRE'


SELECT
    *
FROM
    SPECIF_V_OCS_POSTES

SELECT
    *
FROM
    suiteisilog.OBJET

SELECT
    *
FROM
    Z_LOV_VALUE

SELECT
    U.N_UTIL,
    H.C_FONCTION
FROM
    UTILAFFECTHAB H,
    UTILISATEUR U
WHERE H.T_UTILAFFECT = 'D'
    AND H.C_PROFIL = 'CLIENT' AND H.C_UTIL_DELEGANT=U.C_UTIL
ORDER BY U.N_UTIL,H.C_FONCTION

SELECT
    sum(Q_OBJET)
FROM
    suiteisilog.OBJET
WHERE Q_OBJET > 1
GROUP BY C_REF

SELECT
    O.C_REF,
    sum(O.Q_OBJET) AS QUANTITE
FROM
    suiteisilog.OBJET O
    INNER JOIN suiteisilog.SITE S ON S.C_SITE =O.C_SITE AND S.C_ROLESITE ='P'
WHERE Q_OBJET > 1
GROUP BY O.C_REF

SELECT
    *
FROM
    suiteisilog.SITEFONCTIONNEMENT