SELECT
    left(OS.C_REF, 1) AS CODE_METIER,
    OS.C_REF,
    CASE
        WHEN OS.C_REF IS NULL THEN NULL
        ELSE OS.C_REF + ', ' + ISNULL(CS.L_REF, '') + ', ' + ISNULL(OS.C_BARRE, '') + ', ' + ISNULL(OS.NO_SERIE, '')
    END L_OBJETCOMPLETSERVICE,
    LC.L_NIVEAU,
    CTR.C_TYPECTR,
    --LC.*,
    --CTR.C_DEVISE,
    CTR.L_CTR,
    E.L_EQUIPE,
    E.AD_EQUIPEMAIL,
    --N.L_NATURE,
    --TPB.L_FULLNAMETYPEPB,
    S.L_FULLNAMESITE,
    SERV.L_FULLNAMESERVICE,
    CASE
        WHEN U.PRE_UTIL IS NULL THEN U.N_UTIL
        ELSE U.N_UTIL + ', ' + U.PRE_UTIL
    END AS N_UTILCOMPLET,
    F.L_FAMOBJ,
    T.L_TYPOBJ,
    C.L_REF,
    CASE
        WHEN O.C_REF IS NULL THEN NULL
        ELSE O.C_REF + ', ' + ISNULL(C2.L_REF, '') + ', ' + ISNULL(O.C_BARRE, '') + ', ' + ISNULL(O.NO_SERIE, '')
    END L_OBJETCOMPLET,
    --M.L_MODSERV,
    --NULL AS C_LANGUE,
    --ZM.C_DEFDOCOLE,
    --ZD.N_DOCOLE,
    --ZD.T_DOCOLE,
    --CTR.C_TYPECTR,
    /*suiteisilog.ISIGETLOVVALUE(
     'TYPEPAIEMENTLIGNECTR',
     LC.T_FINLIGNECTR
     ) L_FINLIGNECTR,
     suiteisilog.ISIGETLOVVALUE('UNITE_DE_DUREE', CTR.U_DUCTR) UNITE,*/
    TA.L_TACTION
    /*,
     suiteisilog.ISIGETLOVVALUE(
     'QUALIF_INC',
     LC.C_QUALIFICATIFLCTR
     ) AS L_QUALIFICATIFLCTR,*/
    --TVA.L_CODETVA,
    /*CASE
     WHEN C.C_REF IS NULL THEN NULL
     ELSE C.C_REF + ', ' + ISNULL(C.L_REF, '') + ', ' + ISNULL(SOC.N_SOCIETE, '')
     END L_REFERENCECOMPLET,
     F.C_FAMPERE,
     GR.L_FAMOBJ AS L_FAMPERE*/
FROM suiteisilog.LIGNECTR LC
    LEFT JOIN suiteisilog.NATURE N ON LC.C_NATURE = N.C_NATURE
    LEFT JOIN suiteisilog.TYPEPB TPB ON LC.C_TYPEPB = TPB.C_TYPEPB
    LEFT JOIN suiteisilog.SITE S ON LC.C_SITE = S.C_SITE
    LEFT JOIN suiteisilog.SERVICE SERV ON LC.C_SERVICE = SERV.C_SERVICE
    LEFT JOIN suiteisilog.UTILISATEUR U ON LC.C_UTIL = U.C_UTIL
    LEFT JOIN suiteisilog.FAMOBJ F ON LC.C_FAMOBJ = F.C_FAMOBJ
    LEFT JOIN suiteisilog.FAMOBJ GR ON F.C_FAMPERE = GR.C_FAMOBJ
    LEFT JOIN suiteisilog.TYPOBJ T ON LC.C_FAMOBJ = T.C_FAMOBJ AND LC.C_TYPOBJ = T.C_TYPOBJ
    LEFT JOIN suiteisilog.CATALOGUE C ON LC.C_REF = C.C_REF
    LEFT JOIN suiteisilog.OBJET O ON LC.C_OBJET = O.C_OBJET
    LEFT JOIN suiteisilog.CATALOGUE C2 ON O.C_REF = C2.C_REF
    LEFT JOIN suiteisilog.OBJET OS ON LC.C_OBJSERVICE = OS.C_OBJET
    LEFT JOIN suiteisilog.CATALOGUE CS ON OS.C_REF = CS.C_REF
    LEFT JOIN suiteisilog.MODELECONDSERV M ON LC.C_MODSERV = M.C_MODSERV
    LEFT JOIN suiteisilog.CONTRAT CTR ON LC.NO_CTR = CTR.NO_CTR
    LEFT JOIN suiteisilog.Z_MEMO ZM ON LC.C_MEMO = ZM.C_MEMO
    LEFT JOIN suiteisilog.Z_DOCOLE ZD ON ZM.C_DEFDOCOLE = ZD.C_DOCOLE
    LEFT JOIN suiteisilog.TACTION TA ON LC.C_TACTION = TA.C_TACTION
    LEFT JOIN suiteisilog.CODETVA TVA ON LC.C_CODETVA = TVA.C_CODETVA
    LEFT JOIN suiteisilog.SOCIETE SOC ON C.C_CONST = SOC.C_SOCIETE
    LEFT JOIN suiteisilog.EQUIPE E ON E.C_EQUIPE = CTR.C_EQUIPECONTRAT
WHERE
    CTR.C_TYPECTR in('SLA','UC', 'OLA')
    AND LC.D_ARCHIVE IS NULL --AND OS.C_REF = 'PTV0004'
ORDER BY
    OS.C_REF,
    CTR.C_TYPECTR,
    LC.L_NIVEAU