select A.IDT_APPEL, U.N_UTIL,A.D_APPEL,A.DE_SYMPAPPEL,A.C_EQUIPE,A.C_SERVICE_DEM from suiteisilog.APPEL A, UTILISATEUR U
Where  A.C_STAPPEL='N' and A.C_EQUIPE like 'APPRO1%' and A.C_UTIL_DEM=U.C_UTIL  and NOT EXISTS(
SELECT E.C_EQUIPE, U.C_SERVICE
FROM suiteisilog.UTILEQUIP E INNER JOIN suiteisilog.UTILISATEUR U ON E.C_UTIL = U.C_UTIL
WHERE E.C_EQUIPE Like 'APPRO1%' and A.C_EQUIPE = E.C_EQUIPE and left(A.C_SERVICE_DEM,10) = U.C_SERVICE)


select A.IDT_APPEL, U.N_UTIL,A.D_APPEL,A.DE_SYMPAPPEL,A.C_EQUIPE,A.C_SERVICE_DEM from suiteisilog.APPEL A, UTILISATEUR U
Where  A.C_STAPPEL='N' and A.C_EQUIPE like 'APPRO2%' and A.C_UTIL_DEM=U.C_UTIL  and NOT EXISTS(
SELECT E.C_EQUIPE, U.C_SERVICE
FROM suiteisilog.UTILEQUIP E INNER JOIN suiteisilog.UTILISATEUR U ON E.C_UTIL = U.C_UTIL
WHERE E.C_EQUIPE Like 'APPRO2%' and A.C_EQUIPE = E.C_EQUIPE and left(A.C_SERVICE_DEM,8) = U.C_SERVICE)