SELECT
    U.C_FONCTION,
    A.IDT_APPEL,
    U.N_UTIL,
    A.D_APPEL,
    A.DE_SYMPAPPEL,
    A.C_EQUIPE,
    A.C_SERVICE_DEM
FROM
    suiteisilog.APPEL A,
    suiteisilog.UTILISATEUR U
WHERE  A.C_STAPPEL='N' AND A.C_EQUIPE LIKE 'APPRO1%' AND A.C_UTIL_DEM=U.C_UTIL AND NOT EXISTS(
SELECT
        E.C_EQUIPE,
        U.C_SERVICE
    FROM
        suiteisilog.UTILEQUIP E INNER JOIN suiteisilog.UTILISATEUR U ON E.C_UTIL = U.C_UTIL
    WHERE E.C_EQUIPE LIKE 'APPRO1%' AND A.C_EQUIPE = E.C_EQUIPE AND LEFT(A.C_SERVICE_DEM,10) = U.C_SERVICE) order by A.IDT_APPEL

SELECT
    U.C_FONCTION,
    A.IDT_APPEL,
    U.N_UTIL,
    A.D_APPEL,
    A.DE_SYMPAPPEL,
    A.C_EQUIPE,
    A.C_SERVICE_DEM
FROM
    suiteisilog.APPEL A,
    suiteisilog.UTILISATEUR U
WHERE  A.C_STAPPEL='N' AND A.C_EQUIPE LIKE 'APPRO2%' AND A.C_UTIL_DEM=U.C_UTIL AND NOT EXISTS(
SELECT
        E.C_EQUIPE,
        U.C_SERVICE
    FROM
        suiteisilog.UTILEQUIP E INNER JOIN suiteisilog.UTILISATEUR U ON E.C_UTIL = U.C_UTIL
    WHERE E.C_EQUIPE LIKE 'APPRO2%' AND A.C_EQUIPE = E.C_EQUIPE AND LEFT(A.C_SERVICE_DEM,8) = U.C_SERVICE)