select I_UTI_MATRICULERH,PRE_UTIL, N_UTIL, C_EQUIPEPRIV,C_UTIL from UTILISATEUR where C_EQUIPEPRIV  = 'CLIENT'and C_UTIL in (select C_UTIL FROM UTILAFFECTHAB WHERE C_PROFIL IN ('INTERVENAN','GEST') AND D_ARCHIVE IS NULL ) AND D_ARCHIVE IS NULL

select C_UTIL, C_PROFIL,* FROM UTILAFFECTHAB WHERE C_PROFIL IN ('INTERVENAN','GEST') AND C_UTIL='79156' AND D_ARCHIVE IS NULL --group by  C_UTIL, C_PROFIL