SELECT
    I_UTI_MATRICULERH,
    PRE_UTIL,
    N_UTIL,
    C_EQUIPEPRIV,
    C_UTIL,
    D_MAJENREG
FROM
    UTILISATEUR
WHERE C_EQUIPEPRIV  = 'CLIENT'AND C_UTIL IN (SELECT
        C_UTIL
    FROM
        UTILAFFECTHAB
    WHERE C_PROFIL IN ('INTERVENAN','GEST') AND D_ARCHIVE IS NULL ) AND D_ARCHIVE IS NULL