SELECT
    C.C_REF,
    C.L_REF
FROM
    CATALOGUE C
WHERE C.D_ARCHIVE IS NULL AND C.C_NATUREOBJ='INF' AND C.C_NATURE='REF' AND C.C_REF NOT IN(

SELECT
        O.C_REF
    FROM
        OBJET O
    WHERE O.C_NATURE='INF' AND O.D_ARCHIVE IS NULL
    GROUP BY O.C_REF)

