

SELECT
   A.C_SERVICE_DEM
   ,S.L_FULLNAMESERVICE
  ,A.IDT_APPEL
  ,A.C_EQUIPE 
FROM [IWSPROD].[suiteisilog].[APPEL] A INNER JOIN [IWSPROD].[suiteisilog].[OBJET] O ON O.C_OBJET = A.C_OBJETSERVICE INNER JOIN suiteisilog.SERVICE S On A.C_SERVICE_DEM=S.C_SERVICE
WHERE
A.ST_APPROBATION <> 'V'
AND A.C_STAPPEL Not in ('C','CT')
--AND O.C_BARRE like 'I%'
AND C_EQUIPE LIKE 'A%'
AND A.C_SERVICE_DEM + A.C_EQUIPE NOT IN ( SELECT C_SERVICE + C_EQUIPE
FROM
  (select Z.C_SERVICE, H.C_TYPEHAB
  from suiteisilog.UTILAFFECTHAB H, suiteisilog.Z_SERVICEHIER Z
  WHERE H.ST_UTILAFFECT ='A' AND H.C_SERVICE=Z.C_SERVICEHIER  ) HAB,

  (SELECT T.C_TYPEHAB, C_EQUIPE
  FROM suiteisilog.TYPEHAB T, suiteisilog.TYPEHABEQUIPE E
  WHERE T.C_TYPEHAB=E.C_TYPEHAB AND E.C_EQUIPE like 'APP%') EQ
WHERE HAB.C_TYPEHAB=EQ.C_TYPEHAB)
Order By C_SERVICE_DEM,C_EQUIPE


