

SELECT
   A.C_SERVICE_DEM
   ,S.L_FULLNAMESERVICE
   ,LEFT(O.C_REF,2) AS METIER
  ,A.IDT_APPEL
  ,'https://lgme.sdis13.fr/IsilogWebSystem/HOMEPAGE.aspx?C_ECRAN=HELP005_INC_SYS&Type=LINK&Action=C&FieldName=IDT_APPEL&FieldValue=' + A.IDT_APPEL
  ,A.C_EQUIPE 
  ,O.C_REF
  ,A.D_APPEL
FROM [suiteisilog].[APPEL] A INNER JOIN [suiteisilog].[OBJET] O ON O.C_OBJET = A.C_OBJETSERVICE INNER JOIN suiteisilog.SERVICE S On A.C_SERVICE_DEM=S.C_SERVICE
WHERE
A.ST_APPROBATION <> 'V'
AND A.C_STAPPEL Not in ('C','CT','B')
--AND O.C_BARRE like 'I%'
--AND C_EQUIPE LIKE '%APPR%'
AND A.C_SERVICE_DEM + A.C_EQUIPE NOT IN ( SELECT C_SERVICE + C_EQUIPE
FROM
  (select Z.C_SERVICE, H.C_TYPEHAB
  from suiteisilog.UTILAFFECTHAB H, suiteisilog.Z_SERVICEHIER Z
  WHERE H.ST_UTILAFFECT ='A' AND H.C_SERVICE=Z.C_SERVICEHIER  ) HAB,

  (SELECT T.C_TYPEHAB, C_EQUIPE
  FROM suiteisilog.TYPEHAB T, suiteisilog.TYPEHABEQUIPE E
  WHERE T.C_TYPEHAB=E.C_TYPEHAB /*AND E.C_EQUIPE like '%APPR%'*/) EQ
WHERE HAB.C_TYPEHAB=EQ.C_TYPEHAB)
Order By C_SERVICE_DEM,C_EQUIPE


