select left(S.C_SERVICE,10) as serv,S.L_FULLNAMESERVICE,EQ.C_EQUIPE from suiteisilog.SERVICE S, suiteisilog.EQUIPE EQ
Where  right(S.L_FULLNAMESERVICE,1) <>'-' and left(S.L_FULLNAMESERVICE,5)<> 'ASTRE' and EQ.C_EQUIPE like'APPR%' and EQ.C_EQUIPE not in ('APPRO','APPRO_CDGTPPS','APPRO_CDSPPS','APPRO_GPT')  and NOT EXISTS(
SELECT  U.C_SERVICE
FROM suiteisilog.UTILEQUIP E INNER JOIN suiteisilog.UTILISATEUR U ON E.C_UTIL = U.C_UTIL
WHERE EQ.C_EQUIPE=E.C_EQUIPE and left(S.C_SERVICE,10) = U.C_SERVICE)