SELECT
    F.L_FAMOBJ,
    T.L_TYPOBJ,
    C.L_REF,
    O.C_BARRE,
    O.NB_PARTAGEMAX AS 'Nb licences acquises',
    COUNT(*) As Total,
    O.NB_PARTAGEMAX - COUNT(*) AS Delta
FROM
    suiteisilog.OBJPEREFILS L INNER JOIN suiteisilog.OBJET O ON O.C_OBJET=L.C_OBJET INNER JOIN suiteisilog.CATALOGUE C ON O.C_REF=C.C_REF INNER JOIN suiteisilog.TYPOBJ T ON C.C_TYPOBJ=T.C_TYPOBJ INNER JOIN suiteisilog.FAMOBJ F ON C.C_FAMOBJ=F.C_FAMOBJ
WHERE F.C_FAMPERE='ILOG'
GROUP BY F.L_FAMOBJ,T.L_TYPOBJ,C.L_REF,O.C_BARRE,O.NB_PARTAGEMAX
ORDER BY F.L_FAMOBJ,T.L_TYPOBJ,C.L_REF,O.C_BARRE

--SELECT * FROM suiteisilog.FAMOBJ WHERE C_FAMPERE IS NULL