SELECT TOP (1000) [matricule]
      ,[code_collectivite]
      ,[nom_collectivite]
      ,[num_carrière]
      ,[libellé_carrière]
      ,[date_debut]
      ,[date_fin]
      ,[pourcentage_princ]
      ,[code_service_princ]
      ,[libelle_service_princ]
      ,[sigle_service_princ]
      ,[pourcentage_sec]
      ,[code_service_sec]
      ,[libelle_service_sec]
      ,[sigle_service_sec]
      ,[code_motif]
      ,[libelle_motif]
      ,[code_fonction]
      ,[libelle_fonction]
      ,[matricule_responsable]
      ,[code_sg]
      ,[libelle_sg]
  FROM [ODS_PROD].[dbo].[BL_AGENT_SERVICE]
  where matricule = '021818'