SELECT
    O.NO_SERIE,
    S.C_SITEBARRE,
    O.C_SERVICE,
    O.C_BARRE,
    U.I_UTI_MATRICULERH,
    '29/10/2021' AS DATE_GARANTIE,
    '24' AS DUREE_GARANTIE,
    '016285' AS CODE_SOCIETE_GARANTIE,
    '15/12/2021' AS DATE_INSTALLATION,
    'EE' AS STATUT,
    '' AS COMMENTAIRE,
    /*C_FAMOBJ,
    O.C_REF,*/
    K.VA_CARACOBJ
FROM
    OBJET O INNER JOIN CATALOGUE C ON O.C_REF=C.C_REF INNER JOIN SITE S ON S.C_SITE=O.C_SITE LEFT JOIN UTILISATEUR U ON O.C_UTIL=U.C_UTIL INNER JOIN CARACOBJ K ON K.C_OBJET=O.C_OBJET
WHERE C.C_FAMOBJ='IABOMOB' AND O.D_ARCHIVE IS NULL AND K.C_CARAC='IUTILGEN' AND K.D_HISTCARACOBJ IS NULL 


select D_HISTLIAISON from OBJPEREFILS order by D_HISTLIAISON DESC