/*
SELECT * FROM suiteisilog.UTILAFFECTHAB H
WHERE /*H.C_UTIL = '80524' AND */ H.ST_UTILAFFECT = 'A'
*/

SELECT
    A.IDT_APPEL,A.C_EQUIPE,
    'https://lgme.sdis13.fr/IsilogWebSystem/HOMEPAGE.aspx?C_ECRAN=HELP005_INC_SYS&Type=LINK&Action=C&FieldName=IDT_APPEL&FieldValue=' + A.IDT_APPEL,
    A.C_SERVICE_DEM,
    H.C_UTILAFFECT 
FROM
    suiteisilog.APPEL A
LEFT JOIN suiteisilog.UTILAFFECTHAB H ON A.C_SERVICE_DEM LIKE H.C_SERVICE 
WHERE /* A.IDT_APPEL ='DOS0146334' AND*/A.C_STAPPEL NOT IN ('C','CT','B') AND A.ST_APPROBATION <> 'V' AND H.C_UTILAFFECT IS NULL

