select O.C_REF,L.NO_CTR,L.L_NIVEAU,C.C_TYPECTR from suiteisilog.LIGNECTR L INNER join suiteisilog.OBJET O ON O.C_OBJET=L.C_OBJSERVICE INNER JOIN suiteisilog.CONTRAT C ON L.NO_CTR=C.NO_CTR
WHERE O.C_REF like 'TTRS%' AND L.D_ARCHIVE is null AND C.C_TYPECTR ='OLA' order by O.C_REF,L.L_NIVEAU

