
SELECT
    A.D_CREATION,O.C_REF,C.L_REF,
    CAST(A.D_CREATION AS DATE) AS 'DATE',
    CAST(A.D_CREATION AS TIME(0)) AS 'HEURE',    
    A.IDT_APPEL,
    A.C_OBJET,
    A.C_STAPPEL,
    T.L_STAPPEL,
    A.C_UTIL_INT,
    U.N_UTIL,
    UO.L_FULLNAMESERVICE,
    UO.C_SERVICEBARRE,
    S.CO_SITE,
    S.I_SITE_LATITUDE,
    S.I_SITE_LONGITUDE,
    TP.L_TYPEPB As CATEGORIE,
    A.C_EQUIPE,
    E.L_EQUIPE

FROM
    suiteisilog.APPEL A LEFT JOIN suiteisilog.OBJET O ON A.C_OBJETSERVICE=O.C_OBJET LEFT JOIN suiteisilog.SITE S ON A.C_SITE_DEST=S.C_SITE LEFT JOIN suiteisilog.UTILISATEUR U ON A.C_UTIL_INT=U.C_UTIL LEFT JOIN suiteisilog.TYPEPB TP ON  A.C_TYPEPB=TP.C_TYPEPB left join suiteisilog.SERVICE UO on A.C_SERVICE_DEM=UO.C_SERVICE left join suiteisilog.CATALOGUE C on O.C_REF=C.C_REF left join suiteisilog.STAPPEL T ON A.C_STAPPEL=T.C_STAPPEL left join suiteisilog.EQUIPE E on A.C_EQUIPE=E.C_EQUIPE
WHERE  A.D_ARCHIVE IS NULL AND A.ST_APPROBATION = 'V'

Select min(C_ACTION), min(L_COMMENT) from suiteisilog.ACTIONS ACT where /*ACT.NO_APPEL=256233 and*/ C_TACTION='SYS_AFFECT' and C_EQUIPE='I10' group by NO_APPEL

select NO_APPEL from suiteisilog.APPEL where IDT_APPEL='DOS0158606' 


SELECT
    CASE WHEN S.I_UO_LIBLONG IS NULL
        THEN 'VIDE'
        ELSE S.I_UO_LIBLONG
    END AS GROUPEMENT
FROM
    suiteisilog.Z_SERVICEHIER SH INNER JOIN suiteisilog.SERVICE S ON SH.C_SERVICEHIER=S.C_SERVICE
WHERE SH.C_SERVICE='0303010204' AND SH.NIV_SERVICEHIER=4 