SELECT C.VA_CARACOBJ,O.N_OBJET, LEN(C.VA_CARACOBJ)
FROM suiteisilog.OBJET O
INNER JOIN suiteisilog.CARACOBJ C on O.C_OBJET=C.C_OBJET
WHERE C.C_CARAC='IUTILGEN' AND C.VA_CARACOBJ IS NOT NULL 

select * from suiteisilog.OBJET

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'OBJET' AND COLUMN_NAME LIKE 'I%'

select * from suiteisilog.CARACOBJ WHERE C_CARAC='IUTILGEN'

select C_SITE_DEM,C_SITE_DEST,C_SERVICE_DEM from APPEL WHERE C_UTIL_APP='80524'
