SELECT
    O.N_OBJET,
    O.C_SITE,
    O.C_SERVICE,
    O.C_UTIL,
    U.N_UTIL,
    U.C_ISIPARC,
    O.C_REF,
    H.C_SITE,
    H.C_SERVICE,
    H.C_UTIL,
    H.T_UTILAFFECT,
    H.C_LOV_STATUTPRO
FROM
    suiteisilog.OBJET O LEFT JOIN (SELECT
        *
    FROM
        suiteisilog.QRY_UTILHAB
    WHERE C_PROFIL='CLIENT' ) H ON O.C_SITE = H.C_SITE AND O.C_SERVICE = H.C_SERVICE AND O.C_UTIL =H.C_UTIL INNER JOIN suiteisilog.UTILISATEUR U ON U.C_UTIL=O.C_UTIL
WHERE O.C_NATURE <> 'SERVICE' AND O.D_ARCHIVE IS NULL AND O.C_REF <> 'IILOG0074' /*AND H.C_UTIL IS NULL AND O.C_UTIL IS NOT NULL*/ AND O.C_UTIL='80524'
ORDER BY H.T_UTILAFFECT DESC