SELECT A.C_ACTION, A.NO_APPEL, A.D_CREATION, A.D_ARCHIVE, A.HM_ACTIONREAL, A.J_ACTIONREAL, A.D_MAJENREG, A.HM_ACTIONPREV, A.J_ACTIONPREV, A.D_ACTIONPREV, A.D_ACTIONREAL, A.DF_ACTIONPREV, A.DF_ACTIONREAL, A.L_COMMENT, A.C_STAPPELACT, A.DF_PREVACTIONREAL, A.F_ACTIONREAL, A.VA_ACTCOND, AP.IDT_APPEL,
CASE WHEN CR.L_CIVILITE IS NULL
THEN
CASE WHEN UR.PRE_UTIL IS NULL
THEN UR.N_UTIL
ELSE UR.N_UTIL + ' ' + UR.PRE_UTIL
END
ELSE CR.L_CIVILITE + ' ' +
CASE WHEN UR.PRE_UTIL IS NULL
THEN UR.N_UTIL
ELSE UR.N_UTIL + ' ' + UR.PRE_UTIL
END
END N_UTIL_RESP, E.L_EQUIPE,
CASE WHEN CU.L_CIVILITE IS NULL
THEN
CASE WHEN UU.PRE_UTIL IS NULL
THEN UU.N_UTIL
ELSE UU.N_UTIL + ' ' + UU.PRE_UTIL
END
ELSE CU.L_CIVILITE + ' ' +
CASE WHEN UU.PRE_UTIL IS NULL
THEN UU.N_UTIL
ELSE UU.N_UTIL + ' ' + UU.PRE_UTIL
END
END N_UTIL, SI.N_SITE, SI.L_FULLNAMESITE FULL_SITE, TA.L_TACTION, ST.L_STAPPEL, OPT_URL_MAIL.VA_PARAM MAILIWSPUBLICURL, CS.L_REF L_REFSERVICE, TPB.L_FULLNAMETYPEPB, TPB.L_TYPEPB,
CASE WHEN CD.L_CIVILITE IS NULL
THEN
CASE WHEN UD.PRE_UTIL IS NULL
THEN UD.N_UTIL
ELSE UD.N_UTIL + ' ' + UD.PRE_UTIL
END
ELSE CD.L_CIVILITE + ' ' +
CASE WHEN UD.PRE_UTIL IS NULL
THEN UD.N_UTIL
ELSE UD.N_UTIL + ' ' + UD.PRE_UTIL
END
END N_UTIL_DEM, UD.TEL_UTIL AS TEL_UTIL_DEM, SA.L_FULLNAMESITE, SE.L_FULLNAMESERVICE, AP.DE_SYMPAPPEL, AP.D_APPEL, AP.DE_SOLUTECH, AP.DE_SOLUAPPEL, AP.DE_CAUSEPB, AP.D_CLOTTECH, AP.D_FINPREVUE, AP.D_CLOTURE, AP.L_TITRENEWS, AP.D_REALSOUHAITRFC, AP.VA_VERSION, AP.C_PRIORITE,
CASE WHEN UD.TEL_UTIL IS NULL
THEN ''
ELSE UD.TEL_UTIL + ' - '
END +
CASE WHEN UD.TELP_UTIL IS NULL
THEN ''
ELSE UD.TELP_UTIL + ' - '
END + ISNULL(UD.AD_UTILEMAIL,'') AS VA_COORDONNEES, SD.N_SITE AS N_SITE_DEM, CASE AP.C_NATURE WHEN 'INC'
THEN 'HELP005_INC_SYS' WHEN 'RFC'
THEN 'HELP005_RFC_SYS' WHEN 'FAQ'
THEN 'HELP005_FAQ_SYS' WHEN 'NEWS'
THEN 'HELP005_NEWS_SYS' WHEN 'PB'
THEN 'HELP005_PB_SYS' WHEN 'MEP'
THEN 'HELP005_MEP_SYS'
ELSE 'HELP005_INC_SYS'
END C_ECRANDEST, Y.L_OPERATIONREEL L_MOTIF, ER.L_EQUIPE AS L_EQUIPE_RESP , suiteisilog.GetCommonFilesUrl('Images/CustomImages/LogoIWS.png') LOGO, suiteisilog.GetCommonFilesUrl('Images/CustomImages/cliquer.png') CLIQUEZICI
FROM QRY_ACTIONPREDEC_ACT A
LEFT JOIN TACTION TA
ON A.C_TACTION = TA.C_TACTION
LEFT JOIN EQUIPE E
ON A.C_EQUIPE = E.C_EQUIPE
LEFT JOIN SITE SI
ON A.C_SITE = SI.C_SITE
LEFT JOIN STAPPEL ST
ON A.C_STAPPELACT = ST.C_STAPPEL
LEFT JOIN UTILISATEUR UR
ON A.C_UTIL_RESP = UR.C_UTIL
LEFT JOIN CIVILITE CR
ON UR.C_CIVILITE= CR.C_CIVILITE
LEFT JOIN UTILISATEUR UU
ON A.C_UTIL = UU.C_UTIL
LEFT JOIN CIVILITE CU
ON UU.C_CIVILITE = CU.C_CIVILITE
LEFT JOIN APPEL AP
ON A.NO_APPEL = AP.NO_APPEL
LEFT JOIN OBJET OS
ON AP.C_OBJETSERVICE = OS.C_OBJET
LEFT JOIN CATALOGUE CS
ON OS.C_REF = CS.C_REF
LEFT JOIN TYPEPB TPB
ON AP.C_TYPEPB = TPB.C_TYPEPB
LEFT JOIN UTILISATEUR UD
ON AP.C_UTIL_DEM = UD.C_UTIL
LEFT JOIN CIVILITE CD
ON UD.C_CIVILITE = CD.C_CIVILITE
LEFT JOIN SITE SA
ON AP.C_SITE_DEM = SA.C_SITE
LEFT JOIN SERVICE SE
ON AP.C_SERVICE_DEM = SE.C_SERVICE
LEFT JOIN (
SELECT C_ACTIONPROC,C_INSTPROC,L_OPERATIONREEL
FROM ACTIONS) Y
ON (A.ACTPROCPRED = Y.C_ACTIONPROC
AND A.C_INSTPROC = Y.C_INSTPROC)
LEFT JOIN Z_PARAM OPT_URL_MAIL
ON OPT_URL_MAIL.C_FAMPARAM='Serveur_ME'
AND OPT_URL_MAIL.C_PARAM = 'MAILIWSPUBLICURL'
LEFT JOIN SITE SD
ON UD.C_SITE=SD.C_SITE
LEFT JOIN EQUIPE ER
ON UR.C_EQUIPEPRIV = ER.C_EQUIPE
WHERE E.C_EQUIPE NOT LIKE 'APPRO%'
AND E.C_EQUIPE <> 'CLIENT'
AND AP.C_UTIL_INT IS NULL