	 /*  select N_UTIL,PRE_UTIL,D_SORTIEUTIL,* 
from suiteisilog.UTILISATEUR
WHERE  DATEDIFF(day,D_SORTIEUTIL,GETDATE()) > 0 
--AND
--N_UTIL ='MARCELLE'*/

select N_UTIL,PRE_UTIL,D_SORTIEUTIL,* 
from suiteisilog.UTILISATEUR
WHERE  C_UTIL='83092' AND DATEDIFF(day,D_SORTIEUTIL,GETDATE()) > 0

AND C_UTIL NOT IN (SELECT U.C_UTIL
FROM suiteisilog.UTILISATEUR U 
	INNER JOIN  suiteisilog.OBJET O 
	ON O.C_UTIL = U.C_UTIL AND C_NATURE <> 'SERVICE') 



Select C_UTIL, PRE_UTIL from suiteisilog.UTILISATEUR where N_UTIL='MARCELLE'

SELECT U.* FROM suiteisilog.UTILISATEUR U where N_UTIL='MARCELLE'

SELECt * FROM suiteisilog.UTILAFFECTHAB where C_UTIL='83092'
SELECt * FROM suiteisilog.UTILAFFECTHAB
WHERE I_HAB_RH = 1 AND C_UTIL IN (SELECT C_UTIL FROM suiteisilog.UTILISATEUR WHERE DATEDIFF(day,D_SORTIEUTIL,GETDATE()) > 0) AND C_UTIL='83092'