SELECT C_REFDEM,count(C_REFDEM) AS COMPTE FROM LIGNEDEM /*WHERE C_REFDEM LIKE 'T%'*/ GROUP BY C_REFDEM ORDER BY COMPTE DESC

SELECT D.*,L.* FROM APPEL D INNER JOIN LIGNEDEM L ON D.NO_APPEL=L.NO_APPEL

SELECT * FROM Z_LOV_VALUE WHERE C_LOV_VALUE='P'
SELECT * FROM Z_LOV WHERE L_LOV LIKE '%p%'