Select C_INSTANCEAPP from suiteisilog.INSTANCEAPP where ID_INSTANCEAPP='BCRECORD'

select * from suiteisilog.INSTANCEAPPPARAM WHERE C_INSTANCEAPP = (Select C_INSTANCEAPP from suiteisilog.INSTANCEAPP where ID_INSTANCEAPP='BCRECORD')

select DB_NAME() as [Current Database]

/*UPDATE IP
SET IP.VA_PARAMAPP = DB_NAME()
SET IP.
FROM   INSTANCEAPPPARAM IP
       INNER JOIN INSTANCEAPP I
               ON IP.C_INSTANCEAPP = I.C_INSTANCEAPP
WHERE  IP.C_PARAMAPP = 'DATABASEID'*/

UPDATE IP
SET IP.VA_PARAMAPP = DB_NAME()  FROM   suiteisilog.INSTANCEAPPPARAM IP
       INNER JOIN suiteisilog.INSTANCEAPP I
               ON IP.C_INSTANCEAPP = I.C_INSTANCEAPP
WHERE  IP.C_PARAMAPP = 'DATABASEID' AND I.ID_INSTANCEAPP='BCRECORD'

UPDATE IP
SET IP.VA_PARAMAPP = NULL   FROM   suiteisilog.INSTANCEAPPPARAM IP
       INNER JOIN suiteisilog.INSTANCEAPP I
               ON IP.C_INSTANCEAPP = I.C_INSTANCEAPP
WHERE  IP.C_PARAMAPP = 'PWDACCESS' AND I.ID_INSTANCEAPP='BCRECORD'

