SELECT P.L_PROCED,P.VA_VERSION,A.C_STAPPEL,A.D_CREATION, A.IDT_APPEL,A.ST_APPROBATION,A.C_EQUIPE--, COUNT(A.C_STAPPEL)
  FROM [suiteisilog].[APPEL] A  inner join suiteisilog.INSTPROC I ON A.NO_APPEL=I.NO_APPEL INNER JOIN suiteisilog.PROCED P ON I.C_PROCED=P.C_PROCED
  WHERE A.C_STAPPEL not in ('C','B','CT') AND A.ST_APPROBATION <> 'V' order by A.D_CREATION
 -- Group by P.L_PROCED,P.VA_VERSION ORDER BY P.L_PROCED,P.VA_VERSION

