SELECT
    left(CAT.C_REF, 1) AS CODE_METIER,
    CAT.C_REF,
    CAT.L_REF,
    C.C_TYPECTR,
    L.L_NIVEAU,
    E.L_EQUIPE,
    E.AD_EQUIPEMAIL,
    S.L_FULLNAMESITE
    ,TA.*
    /*,
    L.*,
    C.**/
FROM
    IWSPROD.suiteisilog.LIGNECTR L
    LEFT JOIN IWSPROD.suiteisilog.CONTRAT C ON L.NO_CTR = C.NO_CTR
    LEFT JOIN IWSPROD.suiteisilog.OBJET o on o.C_OBJET = L.C_OBJSERVICE
    LEFT JOIN IWSPROD.suiteisilog.CATALOGUE CAT ON CAT.C_REF = o.C_REF
    LEFT JOIN IWSPROD.suiteisilog.EQUIPE E ON E.C_EQUIPE = C.C_EQUIPECONTRAT
    LEFT JOIN suiteisilog.SITE S ON L.C_SITE=S.C_SITE
    LEFT JOIN suiteisilog.TACTION TA ON TA.C_TACTION=L.C_TACTION
WHERE
    L.D_ARCHIVE IS NULL
    AND C.C_TYPECTR IN ('OLA','UC')
    AND CAT.C_REF='PTV0004'
order by
    CODE_METIER,
    CAT.L_REF,
    L.L_NIVEAU