select A.IDT_APPEL,T.L_STAPPEL,A.C_STAPPEL,A.C_EQUIPE/*, COUNT (A.C_STAPPEL)*/,A.ST_APPROBATION from suiteisilog.APPEL A INNER JOIN suiteisilog.STAPPEL T ON A.C_STAPPEL=T.C_STAPPEL WHERE /*A.C_EQUIPE like '%TRS%' AND A.C_STAPPEL ='AC' */A.C_STAPPEL  in ('DA','AC','B','N') AND A.ST_APPROBATION <> 'V' ORDER BY A.C_STAPPEL--GROUP BY T.L_STAPPEL,A.C_STAPPEL,A.ST_APPROBATION 

--select H.L_TYPEHAB,* from suiteisilog.TYPEHABEQUIPE T  INNER JOIN suiteisilog.TYPEHAB H ON T.C_TYPEHAB = H.C_TYPEHAB where T.C_EQUIPE='CLIENT'

--select O.C_REF,O.C_STOBJ,O.C_PROCED, P.L_PROCED from suiteisilog.OBJET O INNER JOIN suiteisilog.PROCED P ON O.C_PROCED=P.C_PROCED where  O.C_NATURE='SERVICE' AND O.C_STOBJ='EE' AND O.C_PROCED IS NOT NULL

/*select O.C_BARRE,A.* from suiteisilog.LIGNEDEM L INNER JOIN suiteisilog.APPEL A ON L.NO_APPEL=A.NO_APPEL LEFT join suiteisilog.OBJET O on O.C_OBJET=L.C_OBJET

where  L.NO_APPEL=

(select NO_APPEL from suiteisilog.APPEL where IDT_APPEL='DOS0163141')
*/

SELECT 1 FROM suiteisilog.APPEL WHERE C_STAPPEL  IN ('C', 'CT') AND NO_APPEL = 'DOS0136059'