/*select { fn WEEK(A.D_APPEL) } AS Week,UO.I_UO_LIBLONG,L.L_LIGNEDEM,L.VA_CARACVARIANTE,SUM(L.Q_DEMLIGNEDEM) from LIGNEDEM L, APPEL A, OBJET O, SERVICE UO
where L.NO_APPEL=A.NO_APPEL  and O.C_OBJET=A.C_OBJETSERVICE AND O.C_REF in ('PTV0013') AND A.ST_APPROBATION='V' AND A.C_SERVICE_DEM=UO.C_SERVICE
group by { fn WEEK(A.D_APPEL) } ,UO.I_UO_LIBLONG,L.L_LIGNEDEM,L.VA_CARACVARIANTE ORDER by UO.I_UO_LIBLONG

select A.D_APPEL ,UO.I_UO_LIBLONG,L.L_LIGNEDEM,L.VA_CARACVARIANTE,L.Q_DEMLIGNEDEM from LIGNEDEM L, APPEL A, OBJET O, SERVICE UO
where L.NO_APPEL=A.NO_APPEL  and O.C_OBJET=A.C_OBJETSERVICE AND O.C_REF in ('PTV0013') AND A.ST_APPROBATION='V' AND A.C_SERVICE_DEM=UO.C_SERVICE
*/
/*
SELECT N_UTIL,PRE_UTIL,DATEADD(day, 1, GETDATE()) as toto,* FROM suiteisilog.UTILISATEUR
WHERE  DATEDIFF(day,I_UTI_DFINHABP,GETDATE()) > 0 OR DATEDIFF(day,ISNULL(D_SORTIEUTIL,GETDATE()),GETDATE()) >= 0
--WHERE  DATEDIFF(day,I_UTI_DFINHABP,GETDATE()) > 0 OR DATEDIFF(day,D_SORTIEUTIL,GETDATE()) > 0

AND C_UTIL NOT IN (SELECT U.C_UTIL
FROM suiteisilog.UTILISATEUR U 
	INNER JOIN  suiteisilog.OBJET O 
	ON O.C_UTIL = U.C_UTIL
AND  C_NATURE <> 'SERVICE'
    )

DATEADD(day, 1, GETDATE())

SELECT N_UTIL,PRE_UTIL,I_UTI_DFINHABP,D_SORTIEUTIL,*   FROM suiteisilog.UTILISATEUR 
Where DATEDIFF(day,I_UTI_DFINHABP,GETDATE()) > 0 AND D_SORTIEUTIL is null

--WHERE N_UTIL='ALLIONE'
*/

SELECT O.C_BARRE, CC.C_CARAC,CC.VA_CARACOBJ, C.C_TYPOBJ,CCT.VA_CARACOBJ, SO.C_SITEBARRE, SO.L_FULLNAMESITE, SVCO.C_SERVICE, SVCO.L_FULLNAMESERVICE, U.I_UTI_MATRICULERH, U.N_UTIL, U.PRE_UTIL, S.C_SITEBARRE, S.L_FULLNAMESITE, SVC.C_SERVICE, SVC.L_FULLNAMESERVICE,CCUG.VA_CARACOBJ
FROM suiteisilog.OBJET O
	INNER JOIN suiteisilog.CATALOGUE C ON O.C_REF=C.C_REF AND C.C_FAMOBJ='IUNITE' 
	INNER JOIN suiteisilog.CARACOBJ CC ON O.C_OBJET=CC.C_OBJET AND CC.C_CARAC='IANNSORTIE' AND CC.D_HISTCARACOBJ IS NULL
	INNER JOIN suiteisilog.CARACOBJ CCUG ON O.C_OBJET=CCUG.C_OBJET AND CCUG.C_CARAC='IUTILGEN'  AND CCUG.D_HISTCARACOBJ IS NULL
	INNER JOIN suiteisilog.CARACOBJ CCT ON O.C_OBJET=CCT.C_OBJET AND CCT.C_CARAC='ITYPNOUVUC'  AND CCT.D_HISTCARACOBJ IS NULL
	INNER JOIN suiteisilog.SITE SO ON O.C_SITE=SO.C_SITE
	LEFT JOIN suiteisilog.SERVICE SVCO ON O.C_SERVICE=SVCO.C_SERVICE
	LEFT JOIN suiteisilog.UTILISATEUR U on U.C_UTIL=O.C_UTIL
	LEFT join suiteisilog.SITE S on U.C_SITE = S.C_SITE
	LEFT JOIN suiteisilog.SERVICE SVC ON SVC.C_SERVICE=U.C_SERVICE
WHERE O.D_ARCHIVE IS NULL  

