    SELECT
        U.N_UTIL AS 'Nom',
        U.PRE_UTIL AS 'Prénom',
        U.I_UTI_MATRICULERH  AS 'Matricule RH',
        F.L_FONCTION AS 'Fonction',
        S.L_FULLNAMESITE AS 'Site',
        UO.L_FULLNAMESERVICE AS 'UO',
        G.L_LOV_VALUE AS 'Grade',
        STP.L_LOV_VALUE AS 'Statut pro.',
        NULL AS "Statut administration",
        NULL AS 'Identifiant service'

    FROM
        suiteisilog.UTILAFFECTHAB H INNER JOIN suiteisilog.UTILISATEUR U ON H.C_UTIL=U.C_UTIL INNER JOIN suiteisilog.FONCTION F ON H.C_FONCTION=F.C_FONCTION INNER JOIN suiteisilog.Z_LOV_VALUE G ON H.C_LOV_GRADE=G.C_LOV_VALUE INNER JOIN suiteisilog.SITE S ON H.C_SITE=S.C_SITE LEFT JOIN suiteisilog.SERVICE UO ON H.C_SERVICE=UO.C_SERVICE LEFT JOIN suiteisilog.Z_LOV_VALUE STP ON H.C_LOV_STATUTPRO=STP.C_LOV_VALUE
    WHERE /*H.C_UTIL='85476' AND*/ H.C_PROFIL='CLIENT' AND H.D_ARCHIVE IS NULL AND H.ST_UTILAFFECT='A' AND H.C_FONCTION <> 'LGME' AND G.C_LOV='C_LOV_GRADE' AND STP.C_LOV='C_LOV_STATUTPRO' AND U.D_ARCHIVE IS NULL

EXCEPT
    -- COMPLEMENTAIRE
    --INTERSECT
    -- PRINCIPALE
    --UNION

    SELECT
        H.N_UTIL AS 'Nom',
        H.PRE_UTIL AS 'Prénom',
        H.I_UTI_MATRICULERH  AS 'Matricule RH',
        F.L_FONCTION AS 'Fonction',
        S.L_FULLNAMESITE AS 'Site',
        UO.L_FULLNAMESERVICE AS 'UO',
        G.L_LOV_VALUE AS 'Grade',
        STP.L_LOV_VALUE AS 'Statut pro.',
        NULL AS "Statut administration",
        NULL AS 'Identifiant service'

    FROM
        suiteisilog.UTILISATEUR H /*INNER JOIN suiteisilog.UTILISATEUR U ON H.C_UTIL=U.C_UTIL*/ INNER JOIN suiteisilog.FONCTION F ON H.C_FONCTION=F.C_FONCTION INNER JOIN suiteisilog.Z_LOV_VALUE G ON H.C_LOV_GRADE=G.C_LOV_VALUE INNER JOIN suiteisilog.SITE S ON H.C_SITE=S.C_SITE LEFT JOIN suiteisilog.SERVICE UO ON H.C_SERVICE=UO.C_SERVICE LEFT JOIN suiteisilog.Z_LOV_VALUE STP ON H.C_LOV_STATUTPRO=STP.C_LOV_VALUE
    WHERE /*H.C_UTIL='85476' AND*/ H.C_PROFIL='CLIENT' AND H.D_ARCHIVE IS NULL AND G.C_LOV='C_LOV_GRADE' AND (D_SORTIEUTIL > getdate() OR D_SORTIEUTIL IS NULL) AND STP.C_LOV='C_LOV_STATUTPRO'

