SELECT
    A.NO_APPEL,
    A.IDT_APPEL AS  NUMDOSSIER,
    S.N_SITE AS SITE,
    UO.I_UO_LIBLONG AS UO,
    CASE 
        WHEN U.N_UTIL IS NULL
        THEN
        O.I_OBJ_UTILGEN
        ELSE
        U.N_UTIL + ' ' + U.PRE_UTIL
    END AS NOM,
    O.C_BARRE AS OBJET,
    S.I_SITE_LATITUDE AS LATITUDE,
    S.I_SITE_LONGITUDE AS LONGITUDE
FROM
    suiteisilog.APPEL A LEFT JOIN suiteisilog.SITE S ON A.C_SITE_DEST=S.C_SITE LEFT JOIN suiteisilog.SERVICE UO ON A.C_SERVICE_DEM=UO.C_SERVICE LEFT JOIN suiteisilog.OBJET O ON A.C_OBJET=O.C_OBJET LEFT JOIN suiteisilog.UTILISATEUR U ON A.C_UTIL_APP=U.C_UTIL
WHERE A.C_OBJETSERVICE=1678868 -- 1678868 = Renouvellement Poste de travail
AND A.NO_APPEL NOT IN (SELECT ACT.NO_APPEL FROM suiteisilog.ACTIONS ACT WHERE ACT.C_TACTION='I_INTERV_008') AND A.C_STAPPEL not in ('CT','CA') AND A.D_ARCHIVE IS NULL

SELECT N_UTIL,PRE_UTIL FROM suiteisilog.UTILISATEUR WHERE C_UTIL=80524

select A.C_TACTION,D.* from suiteisilog.APPEL D left join suiteisilog.ACTIONS A On D.NO_APPEL=A.NO_APPEL where D.IDT_APPEL='DOS0168769' AND A.C_TACTION  NOT IN (select A.C_TACTION from suiteisilog.APPEL D left join suiteisilog.ACTIONS A On D.NO_APPEL=A.NO_APPEL where D.IDT_APPEL='DOS0168769' AND A.C_TACTION like 'SYS%')

Select S.C_SITEBARRE,S.L_FULLNAMESITE,ST.L_STOBJ,O.* from suiteisilog.OBJET O left join suiteisilog.SITE S on O.C_SITE=S.C_SITE left join suiteisilog.STOBJ ST ON O.C_STOBJ=ST.C_STOBJ where O.C_NATURE='VEH'

SELECT * FROM suiteisilog.ACTIONS A WHERE A.C_TACTION='I_INTERV_001' 

SELECT * FROM suiteisilog.SDIS13_KIZEO


USE [IWSREPRISE]
GO

/****** Object:  View [suiteisilog].[SDIS13_KIZEO]    Script Date: 24/04/2024 15:11:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER  VIEW [suiteisilog].[SDIS13_KIZEO] AS SELECT
    A.NO_APPEL,
	A.IDT_APPEL AS  NUMDOSSIER,
    S.N_SITE AS SITE,
    UO.I_UO_LIBLONG AS UO,
    CASE 
        WHEN U.N_UTIL IS NULL
        THEN
        O.I_OBJ_UTILGEN
        ELSE
        U.N_UTIL + ' ' + U.PRE_UTIL
    END AS NOM,
    O.C_BARRE AS OBJET,
    S.I_SITE_LATITUDE AS LATITUDE,
    S.I_SITE_LONGITUDE AS LONGITUDE
FROM
    suiteisilog.APPEL A LEFT JOIN suiteisilog.SITE S ON A.C_SITE_DEST=S.C_SITE LEFT JOIN suiteisilog.SERVICE UO ON A.C_SERVICE_DEM=UO.C_SERVICE LEFT JOIN suiteisilog.OBJET O ON A.C_OBJET=O.C_OBJET LEFT JOIN suiteisilog.UTILISATEUR U ON A.C_UTIL_APP=U.C_UTIL
WHERE A.C_OBJETSERVICE=1678868 -- 1678868 = Renouvellement Poste de travail
AND A.NO_APPEL NOT IN (SELECT ACT.NO_APPEL FROM suiteisilog.ACTIONS ACT WHERE ACT.C_TACTION='I_INTERV_008') AND A.C_STAPPEL not in ('CT','CA') AND A.D_ARCHIVE IS NULL

GO
